### ISSUE TITLE
Error running locally

### ISSUE THREAD

**Issue by kaustav202** [Abdulmumin1/Merch-Designer#5]
npm run dev throws error

Environment : Windows 10

**Comment by kaustav202** [comment]
![Screenshot (718)](https://user-images.githubusercontent.com/89788120/194262211-59484563-dcf6-42b8-ac21-555e7ec0e4e7.png)

**Comment by Abdulmumin1** [comment]
Are you sure follow the steps?

<ul>
<li>
clone your forked repo
</li>
<li>
run *npm install* in the project directory
</li>

<li>
run  *npm run dev*
</li>
</ul>

**Comment by kaustav202** [comment]
> Owner

Absolutely.. all the dependencies have installed successfully

**Comment by Keith-Web3** [comment]
Hmm, it worked when I forked the project. Have you tried to run the same command on another project? It might be an issue with your system

**Comment by Abdulmumin1** [comment]
@kaustav202 Sync your fork and re clone the project.
If persist:
Update npm: npm install npm@latest -g
If persist: 
attach a screenshot of the log file here!

**Comment by kaustav202** [comment]
> @kaustav202 Sync your fork and re clone the project. If persist: Update npm: npm install npm@latest -g If persist: attach a screenshot of the log file here!

Yup it's working now. Thanks!
